# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fozziejoin_wrappers", use_symbols = TRUE, package_name = "fozziejoin")

#' @usage NULL
#' @useDynLib fozziejoin, .registration = TRUE
NULL

#' Performs a fuzzy join between two data frames based on approximate string matching.
#'
#' This function matches records in `df1` and `df2` using a specified column, allowing
#' matches within a given Levenshtein distance (`max_distance`). It builds index maps
#' for efficient lookup and comparison.
#'
#' # Parameters
#'
#' - `df1` (`List`): The first data frame. Note dataframes are a list of equal-length vectors.
#' - `df2` (`List`): The second data frame.
#' - `by` (`Vec<String>`): A vector containing column names to join on.
#'   - `by[0]`: Column name in `df1`.
#'   - `by[1]`: Column name in `df2`.
#' - `max_distance` (`i32`): The maximum allowable Levenshtein distance for a match.
#'
#' # Returns
#'
#' - `Robj`: A data frame containing matched records from both `df1` and `df2`,
#'   with column names suffixed as `.x` (from `df1`) and `.y` (from `df2`).
#'
#' # Example
#'
#' ```rust
#' use extendr_api::prelude::*;
#'
#' fn main() {
#'     let df1 = List::from_values(vec![
#'         ("name".to_string(), Robj::from(vec!["apple", "banana", "cherry"]))
#'     ]);
#'
#'     let df2 = List::from_values(vec![
#'         ("name".to_string(), Robj::from(vec!["appl", "bananna", "berry"]))
#'     ]);
#'
#'     let result = fuzzy_join(df1, df2, vec!["name".to_string(), "name".to_string()], 2);
#'     println!("{:?}", result);
#' }
#' ```
#'
#' # Notes
#'
#' - This function leverages **parallel iteration** (`par_iter()`) for performance optimization.
#' - Ensures minimal redundant comparisons by only comparing unique values.
#' - Only compares strings whose difference in length is within the user-specified max distance.
#' - The resulting data frame maintains column alignment while allowing fuzzy matching.
#'
#' # See Also
#'
#' - [`levenshtein`](https://docs.rs/levenshtein/latest/levenshtein/) - Used for calculating string distances.
#' - [`extendr`](https://extendr.github.io/) - Enables Rust to interface with R.
#' - [`data_frame!`](https://extendr.github.io/) - Constructs an R-compatible data frame.
#'
#' @export
fozzie_join <- function(df1, df2, by, max_distance) .Call(wrap__fozzie_join, df1, df2, by, max_distance)


# nolint end
