# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fozziejoin_wrappers", use_symbols = TRUE, package_name = "fozziejoin")

#' @usage NULL
#' @useDynLib fozziejoin, .registration = TRUE
NULL

#' @export
fozzie_string_join_rs <- function(df1, df2, by, method, how, max_distance, distance_col, q, max_prefix, prefix_weight, nthread) .Call(wrap__fozzie_string_join_rs, df1, df2, by, method, how, max_distance, distance_col, q, max_prefix, prefix_weight, nthread)

#' @export
fozzie_difference_join_rs <- function(df1, df2, by, how, max_distance, distance_col, nthread) .Call(wrap__fozzie_difference_join_rs, df1, df2, by, how, max_distance, distance_col, nthread)

#' @export
fozzie_distance_join_rs <- function(df1, df2, by, method, how, max_distance, distance_col, nthread) .Call(wrap__fozzie_distance_join_rs, df1, df2, by, method, how, max_distance, distance_col, nthread)

#' @export
fozzie_interval_join_rs <- function(df1, df2, by, how, overlap_type, maxgap, minoverlap, interval_mode, nthread) .Call(wrap__fozzie_interval_join_rs, df1, df2, by, how, overlap_type, maxgap, minoverlap, interval_mode, nthread)


# nolint end
